### PR TITLE
migrate to latest nan

### PR DESCRIPTION
**Pull request by pasupulaphani**
Currently the lib is failing to install due to incompatibility. Started making changes as per the new NAN.

pending with bunch of errors like - 

```
  CXX(target) Release/obj.target/binding/src/py_object_wrapper.o
../src/py_object_wrapper.cc:22:38: error: cannot initialize a parameter of type 'NamedPropertyGetterCallback' (aka 'void (*)(Local<v8::String>, const
      PropertyCallbackInfo<v8::Value> &)') with an lvalue of type 'Nan::NAN_GETTER_RETURN_TYPE (v8::Local<v8::String>, Nan::NAN_GETTER_ARGS_TYPE)' (aka 'void
      (Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)'): type mismatch at 2nd parameter ('const PropertyCallbackInfo<v8::Value> &'
      (aka 'const v8::PropertyCallbackInfo<v8::Value> &') vs 'Nan::NAN_GETTER_ARGS_TYPE' (aka 'const PropertyCallbackInfo<v8::Value> &'))
    obj_tpl->SetNamedPropertyHandler(Get, Set);
                                     ^~~
```

Any help in fixing these errors is much appreciated.

### CODE REVIEW

**Comment by pasupulaphani** [comment]
@stefankutko there are still few errors to resolve :/

**Comment by mateodelnorte** [comment]
Thanks @pasupulaphani. Can you bullet out the current list of TODO's here?

I may have time to lend a hand.

**Comment by pasupulaphani** [comment]
hi @mateodelnorte , thank u.

py_object_wrapper.cc is the file that still require some migration to latest "nan" to be done.

I compiled using node 4.5 and tried running a python command using the binding. It failed. I'm getting some segment faults as well few times :(

**Comment by mateodelnorte** [comment]
Hi @pasupulaphani. How much additional work do you think there is left here?

**Comment by pasupulaphani** [comment]
Huge unknown. As new issues pop up. From what I know this would be easier for someone experienced in writing bindings.

**Pull request merged**
